# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_complete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomplete',
            name='text_len',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
